version: '3'

services:
  beacon:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    command: npm run serve
  db:
    image: mongo
    expose:
      - 27017
    volumes:
      - ./data/db:/data/db
